<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css"/>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>

<div class="text-1e2022 font-size-20 mb-2 font-weight-semi-bold">Write a review</div>
<div class="d-md-flex">
    <div class="text-1e2022 font-size-1 d-md-flex align-items-md-center">How much do you like this product? <span style="color: red; margin-left: 0.5rem">*</span></div>
    <div class="rating ml-md-2">
        <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
        <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
        <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
        <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
        <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
    </div>
</div>
<form id="myForm">
    <div class="block block-dashboard-info">
        <div class="block-content">
            <div class="box box-information">
                <div class="font-size-1 text-1e2022 mb-1">Select an extension to review <span
                        style="color: red">*</span></div>

                <select class="selectpicker mb-2" data-live-search="true">
                    <option value="" selected disabled>Please select</option>
                    <option value="1">Luna test</option>
                    <option value="2">Tom test</option>
                    <option value="3">Jonh test</option>
                    <option value="4">Ry test</option>
                    <option value="5">Helo test</option>
                </select>

                <div class="font-size-1 text-1e2022 mb-1">Company</div>
                <input type="text" id="company" name="company" class="border-radius-4 border-adadad mb-2">
            </div>

            <div class="box box-information">
                <div class="font-size-1 text-1e2022">Your review</div>
                <textarea class="border-adadad border-radius-4"></textarea>
                <div class="text-4bde" style="font-size: 14px">Your review should be at least 30 words long</div>
            </div>
        </div>

        <button id="review-button" type="submit" class="mt-4 db-bg-navy text-white py-2" style="border-radius: 6px;">Submit review</button>
    </div>
</form>

<style>
    @media (min-width: 768px) {
        .d-md-flex {
            display: flex;
        }

        .align-items-md-center {
            align-items: center;
        }

        .ml-md-2 {
            margin-left: 1rem !important;
        }
    }

    .rate {
        border-bottom-right-radius: 12px;
        border-bottom-left-radius: 12px
    }

    .rating {
        display: flex;
        flex-direction: row-reverse;
        justify-content: start
    }

    .rating > input {
        display: none
    }

    .rating > label {
        position: relative;
        width: 1em;
        font-size: 30px;
        font-weight: 300;
        color: #FFD600;
        cursor: pointer
    }

    .rating > label::before {
        content: "\2605";
        position: absolute;
        opacity: 0
    }

    .rating > label:hover:before,
    .rating > label:hover ~ label:before {
        opacity: 1 !important
    }

    .rating > input:checked ~ label:before {
        opacity: 1
    }

    .rating:hover > input:checked ~ label:before {
        opacity: 1
    }

    .buttons {
        top: 36px;
        position: relative
    }


    .btn-default:hover {
        background-color: white !important;
        border-color: #ADADAD !important;
    }

    .bootstrap-select .btn:focus {
        outline: none !important;
        outline: unset !important;
        outline-offset: 0 !important;
    }

    .bootstrap-select:not([class*=col-]):not([class*=form-control]):not(.input-group-btn) {
        width: -webkit-fill-available !important;
    }

    .text-1e2022 {
        color: #1E2022;
    }

    .text-4bde {
        color: #4B4D4E;
    }

    .text-white {
        color: white !important;
    }

    .border-radius-4 {
        border-radius: 4px;
    }

    .border-adadad {
        border: 1px solid #ADADAD;
    }

    .font-size-1 {
        font-size: 16px;
    }

    .font-size-20 {
        font-size: 20px;
    }

    .mb-2 {
        margin-bottom: 1rem !important;
    }

    .mb-1 {
        margin-bottom: 0.5rem !important;
    }

    .mt-4 {
        margin-top: 2rem !important;
    }

    .py-2 {
        padding-top: 1rem !important;
        padding-bottom: 1rem !important;
    }

    .font-weight-semi-bold {
        font-weight: 600;
    }

    input.border-radius-4 {
        border-radius: 4px !important;
    }

    .db-bg-navy {
        background-color: navy !important;:;
    }
</style>
