<div class="text-1e2022 font-size-20 mb-2 font-weight-semi-bold">Write a review</div>
<div class="d-md-flex">
    <div class="text-1e2022 font-size-1 d-md-flex align-items-md-center">How much do you like this product? <span style="color: red; margin-left: 0.5rem">*</span></div>
    <div class="rating ml-md-2">
        <input type="radio" name="rating" value="5" id="5" checked><label for="5">☆</label>
        <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
        <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
        <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
        <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
    </div>
</div>
<form id="review-form">
    <div class="block block-dashboard-info">
        <div class="block-content">
            <div class="box box-information">
                <div class="font-size-1 text-1e2022 mb-1">Select an extension to review <span style="color: red">*</span></div>
                <select class="selectpicker mb-2" data-live-search="true" required>
                    <option value="" selected disabled>Please select</option>
                    <option value="1">Luna test</option>
                    <option value="2">Tom test</option>
                    <option value="3">Jonh test</option>
                    <option value="4">Ry test</option>
                    <option value="5">Helo test</option>
                </select>
                <p id="error-message">Please select an option before submitting the review.</p>

                <div class="font-size-1 text-1e2022 mb-1">Company</div>
                <input type="text" id="company" name="company" class="border-radius-4 border-adadad mb-2">
            </div>

            <div class="box box-information">
                <div class="font-size-1 text-1e2022">Your review</div>
                <textarea class="border-adadad border-radius-4"></textarea>
                <div class="text-4bde" style="font-size: 14px">Your review should be at least 30 words long</div>
            </div>
        </div>

        <button id="review-button" type="submit" class="mt-4 db-bg-navy text-white py-2" style="border-radius: 6px;">Submit review</button>
        <p id="success-message">Your review has been successfully submitted, and will be displayed soon</p>
    </div>
</form>
